LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_cameraroom_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_design_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_toolroom_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_comms_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_server_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_newoffice_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_bay1left_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_bay1right_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_bay2left_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_logistics_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/sta_comms_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/ply_comms_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/ply_warehouse_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/ald_comms_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/craw_comms_switch.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_sgesxi1_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_sgesxi2_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_sgesxi3_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_sgesxi4_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_esx1_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_esx2_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_esx3_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_esx4_host.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_alpha_nas.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_beta_nas.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_gamma_nas.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_epsilon_nas.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_eta_nas.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_zeta_nas.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/man_equalogic_san.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/ply_delta_nas.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
LANG=C LC_ALL=C /usr/bin/mrtg /etc/mrtg/ply_equalogic_san.cfg --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
